matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      group: edge
      compiler: clang

language: c

branches:
  only:
    - master

cache:
  directories:
    - "./node_modules"
    - "${HOME}/.yarn-cache"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - libxss-dev:i386
      - rpm
      - snapd
      - xz-utils

env:
  - PATH=/snap/bin:$PATH

before_install:
  - echo "🔧 Setting up Node"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 12.8.0 && nvm use 12.8.0
  - npm --global update npm
  - npm --global install yarn

install:
  - echo "🚦 Preparing Environment"
  - sudo snap install snapcraft --classic
  - echo "📥 Installing Dependencies"
  - yarn install

script:
  - echo "📦 Building"
  - npm run build --metadata

after_success:
  - echo "📮 Deploying to Github"
  - npm run deploy

notifications:
  webhooks:
    on_failure: always
    on_start: never
    on_success: change
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
